name: expenses-tracker
services:
    database:
        container_name: expenses-tracker-database
        image: postgres:16
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: expenses-tracker
            DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/expenses-tracker
        command:
            [
                'postgres',
                '-c',
                'shared_buffers=32MB',
                '-c',
                'work_mem=4MB',
                '-c',
                'max_connections=20',
            ]
        deploy:
            resources:
                limits:
                    memory: 128M
        restart: unless-stopped
        ports:
            - '127.0.0.1:5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - expenses-tracker-net

networks:
    expenses-tracker-net:

volumes:
    pgdata:
