name: expenses-tracker
services:
    app:
        container_name: expenses-tracker-app
        build: .
        restart: unless-stopped
        networks:
            - proxy

networks:
    proxy:
        external: true
