services:
    server:
        container_name: expense-api
        build: ./server
        restart: unless-stopped
        networks:
            - proxy
            - expense-tracker-net

    client:
        container_name: expense-client
        build: ./client
        restart: unless-stopped
        depends_on:
            - server
        networks:
            - proxy
            - expense-tracker-net

networks:
    proxy:
        external: true
    expense-tracker-net:
