services:
    server:
        container_name: expenses-api
        build: ./server
        restart: unless-stopped
        networks:
            - proxy
            - expenses-tracker-net

    client:
        container_name: expenses-client
        build: ./client
        restart: unless-stopped
        depends_on:
            - server
        networks:
            - proxy
            - expenses-tracker-net

networks:
    proxy:
        external: true
    expenses-tracker-net:
